### ISSUE TITLE
Building for SailfishOS-4.4.0.58-aarch64

### ISSUE THREAD

**Issue by syedmizanur** [foolab/quran#2] opened 2022-06-20 14:21 UTC
Hi, 
Thank you very much for the Quran App for Sailfish OS. 

I was trying to build the code for SailfishOS-4.4.0.58-aarch64 with the command
sfdk build 
and got the following error
Cannot read /home/mizanursyed/code/quran/quazip/quazip/quazip.pri: No such file or directory
+ make
make: *** No rule to make target '../ffmpeg/configure', needed by 'ffmpeg_arm64_build'.  Stop.
error: Bad exit status from /var/tmp/rpm-tmp.JBmADk (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.JBmADk (%build)

Your help would be very much appreciated!

Best Regards,
Syed

**Comment by foolab** [comment] 2022-06-20 15:00
wow!
Good to see that I still have Sailfish OS users.

You are missing the submodules:
`
git submodule update --init --recursive
`

**Comment by syedmizanur** [comment] 2022-06-21 11:22
Hi,

Thanks for the prompt response. Yes, I have been using your app on my previous Sailfish devices for years now. Jazak Allahu Khairan! However, I dont find it on the Store on my new Xperia X III and thought I may have to build it myself.

I tried the git submodules update and don't have the missing rule anymore. However, the build command terminated with this error 

In file included from ../common/translations.cpp:22:
../common/downloader.h:74:8: error: field ‘m_url’ has incomplete type ‘QUrl’
   QUrl m_url;
        ^~~~~
In file included from /home/(homedir)/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtCore/qobject.h:48,
                 from /home/(homedir)SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtCore/QObject:1,
                 from ../common/translations.h:21,
                 from ../common/translations.cpp:18:
/home/(homedir)SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtCore/qmetatype.h:1887:1: note: forward declaration of ‘class QUrl’
 QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:1182: translations.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.6cys9Y (%build)


Thanks,
Syed

**Comment by foolab** [comment] 2022-06-22 06:49
Sorry for that. I pushed a fix. Please report any other issues :)

**Comment by syedmizanur** [comment] 2022-06-22 10:55
Thanks for the reply. I updated the repo and tried to build again and got this message


g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -march=armv8-a -std=gnu++1y -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -D__STDC_CONSTANT_MACROS -DVERSION=\"0.8.0\" -DPULSE -DDATA_DIR=\"/home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/share/harbour-quran/\" -DSAILFISH=1 -D_REENTRANT -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../ffmpeg -Iffmpeg/arm64 -I../sqlite -I../quazip/quazip -I. -I../data -I../common -I../common/interfaces -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/uuid -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/freetype2 -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/libpng16 -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/mdeclarativecache5 -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtSensors -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5 -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtCore -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/resource/qt5 -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/resource -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtQuick -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtGui -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtQml -isystem /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/include/qt5/QtNetwork -I. -I/usr/share/qt5/mkspecs/linux-g++ -o downloader.o ../common/downloader.cpp
../common/downloader.cpp: In member function ‘void Download::setReply(QNetworkReply*)’:
../common/downloader.cpp:94:8: error: ‘qOverload’ was not declared in this scope
        qOverload<>(&QNetworkReply::ignoreSslErrors));
        ^~~~~~~~~
../common/downloader.cpp:94:18: error: expected primary-expression before ‘>’ token
        qOverload<>(&QNetworkReply::ignoreSslErrors));
                  ^
make: *** [Makefile:1194: downloader.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.mXgkHq (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.mXgkHq (%build)


Thanks for the support. Appreciate it!

Best Regards,
Syed

**Comment by foolab** [comment] 2022-06-22 20:13
I pushed a few commits to master and now it builds.
I am however unable to build an RPM as I do not have the SDK to inspect this failure: https://build.sailfishos.org/package/live_build_log/home:msameer:sailfish:apps/harbour-quran/sailfishos_latest_latest_aarch64/aarch64

Nor do I have Sailfish OS 4

Could you help with that?

An alternative is to rebuild the 0.7 tag for aarch64 (Should be doable via OBS too).

But please note that I have not tested if it will run or not.
I switched to an Android phone unfortunately but I would love to keep SFOS alive

**Comment by syedmizanur** [comment] 2022-06-23 12:33
Hi,

I tried to build it with the SDK and got the same error message as on OBS. If you let me know which steps to perform to help you understand the issue, I can try them on my side. 

Thanks Again for your time.

Best,
Syed

Error 
cd ../data/text/ && /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/lib64/qt5/bin/qmake && make gen
make[1]: Entering directory '/home/mizanursyed/code/quran/data/text'
make[1]: Nothing to be done for 'gen'.
make[1]: Leaving directory '/home/mizanursyed/code/quran/data/text'
cd ../data/search/ && /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/lib64/qt5/bin/qmake && make gen
make[1]: Entering directory '/home/mizanursyed/code/quran/data/search'
make[1]: Nothing to be done for 'gen'.
make[1]: Leaving directory '/home/mizanursyed/code/quran/data/search'
g++ -Wl,-O1 -o harbour-quran qioapi.o JlCompress.o quaadler32.o quacrc32.o quagzipfile.o quaziodevice.o quazip.o quazipdir.o quazipfile.o quazipfileinfo.o quazipnewinfo.o unzip.o zip.o bookmarks.o dataprovider.o numberformatter.o settings.o quranviewmodel.o aboutdata.o textsupplier.o translations.o translation.o downloader.o textprovider.o index.o recitations.o recitation.o mediaplaylist.o main.o flipsensor.o mediaplayer.o iconprovider.o media.o audiooutput.o mediadecoder.o bookmarksmodel.o bookmarkitem.o mediaresampler.o searchmodel.o models.o coreapplication.o metadata.o chapterinfo.o partinfo.o pageinfo.o pageposition.o normalize.o chapterlistmodel.o partlistmodel.o mediacodec.o recitationdataprovider.o mediaplayerconfig.o mediaplayback.o quran.o pulse.o fsmonitor.o audiopolicy.o application.o mediaservice.o networkmanager.o qrc_data.o qrc_theme.o qrc_logo.o qrc_sailfish.o qrc_icons.o qrc_qml.o moc_quagzipfile.o moc_quaziodevice.o moc_quazipfile.o moc_bookmarks.o moc_dataprovider.o moc_numberformatter.o moc_settings.o moc_quranviewmodel.o moc_aboutdata.o moc_textsupplier.o moc_translations.o moc_translation.o moc_downloader.o moc_recitations.o moc_recitation.o moc_mediaplaylist.o moc_flipsensor.o moc_mediaplayer.o moc_audiooutput.o moc_mediadecoder.o moc_bookmarksmodel.o moc_bookmarkitem.o moc_mediaresampler.o moc_searchmodel.o moc_models.o moc_chapterinfo.o moc_partinfo.o moc_pageinfo.o moc_pageposition.o moc_chapterlistmodel.o moc_partlistmodel.o moc_mediacodec.o moc_mediaplayback.o moc_quran.o moc_pulse.o moc_fsmonitor.o moc_audiopolicy.o moc_mediaservice.o   -Wl,--start-group ffmpeg/arm64/libavcodec/libavcodec.a ffmpeg/arm64/libavformat/libavformat.a ffmpeg/arm64/libavutil/libavutil.a ffmpeg/arm64/libavfilter/libavfilter.a ffmpeg/arm64/libswresample/libswresample.a -Wl,--end-group sqlite/arm64/.libs/libsqlite3.a -lz -Wl,-rpath=/usr/share/harbour-quran/lib/ -lfreetype -lpulse -pie -rdynamic -lmdeclarativecache5 -lQt5Sensors -lfontconfig -L//usr/lib64 -lresourceqt5 -ldbus-qeventloop-qt5 -ldbus-1 -lresource -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread 
install -m 755 -p harbour-quran /home/deploy/installroot/usr/bin/harbour-quran
: /home/deploy/installroot/usr/bin/harbour-quran
+ popd
/home/mizanursyed/code/quran
+ mkdir -p /home/deploy/installroot//usr/share/harbour-quran/data/
+ cp data/search.db /home/deploy/installroot//usr/share/harbour-quran/data/
+ mkdir -p /home/deploy/installroot//usr/share/harbour-quran/fonts/
+ cp -a data/amiri-quran.ttf /home/deploy/installroot//usr/share/harbour-quran/fonts/
+ cp -a data/amiri-regular.ttf /home/deploy/installroot//usr/share/harbour-quran/fonts/
+ cp -a data/fonts.conf /home/deploy/installroot//usr/share/harbour-quran/fonts/
+ mkdir -p /home/deploy/installroot//usr/share/icons/hicolor/86x86/apps/
+ mkdir -p /home/deploy/installroot//usr/share/applications/
+ mkdir -p /home/deploy/installroot//usr/share/harbour-quran/lib/
+ cp /home/mizanursyed/code/quran/rpm/harbour-quran.png /home/deploy/installroot//usr/share/icons/hicolor/86x86/apps/
+ cp /home/mizanursyed/code/quran/rpm/harbour-quran.desktop /home/deploy/installroot//usr/share/applications/
+ desktop-file-install --delete-original --dir /home/deploy/installroot/usr/share/applications /home/deploy/installroot/usr/share/applications/harbour-quran.desktop
+ cp /home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/lib/libdbus-glib-1.so.2.2.2 /home/deploy/installroot//usr/share/harbour-quran/lib/libdbus-glib-1.so.2
cp: cannot stat '/home/mizanursyed/SailfishOS/mersdk/targets/SailfishOS-4.4.0.58-aarch64.default/usr/lib/libdbus-glib-1.so.2.2.2': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.nogAGp (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.nogAGp (%install)

**Comment by foolab** [comment] 2022-06-23 21:25
The problem is the move to aarch64 changed the paths for bundled libraries.

I bundle libraries because some of the APIs used are not allowed by sailfish OS (not white listed).

I have dropped all of the bundled libraries and managed to build an RPM here: https://build.sailfishos.org/package/binary/home:msameer:sailfish:apps/harbour-quran?arch=aarch64&filename=harbour-quran-0.7.0%2Bmaster.20220623205801.153.g93f59d6-118.1.aarch64.rpm&repository=sailfishos_latest_latest_aarch64

I do not have a sailfish 4 phone so I cannot test the app.
The problem now is I tried walking the chain of dependencies to bundle them but I ended up with libsystemd which in my opinion should not be bundled. I don't know what to do but it seems I will have to drop harbour support. Is openrepos.net still alive?

**Comment by syedmizanur** [comment] 2022-06-26 06:33
Hello,

sorry for the delayed reponse - was feeling a bit under the weather. 

The build.sailfish.org link does not show any downloadable RPMs. I see this 404 Not Found Error when I follow the link to the download repositories - 
https://repo.sailfishos.org/obs/home:/msameer:/sailfish:/apps/sailfishos_latest_latest_aarch64

Openrepos is still up and works quite well btw.

Completely understand your constraints - The OS has evolved quite a bit now (Sailjail, aarch64, QT changes...) and it would be tough to support something with such a limited user base. I guess I can just use a pdf of the Mashaf (which is definitely better than Ad riddled / Privacy unfriendly APKs out there-)

Anyway, as a last try: if you can share the aarch64 build rpm with me, I could try testing it on my phone to see if it works. 

Best Regards,
Syed

**Comment by foolab** [comment] 2022-06-26 08:53
No worries :)
The link I posted is this one:
https://build.sailfishos.org/package/binary/home:msameer:sailfish:apps/harbour-quran?arch=aarch64&filename=harbour-quran-0.7.0%2Bmaster.20220623205801.153.g93f59d6-118.1.aarch64.rpm&repository=sailfishos_latest_latest_aarch64
You can click on the RPM name up there to download it.
I do not know why OBS is not publishing the build results and I am unable to investigate it right now.

I am fine keeping the Sailfish OS version alive. I'd love to but someone will have to do the testing.
I can also try to submit the Android version to harbour. It is ironic and sad that getting the Android APK is easier than the native app :(

**Comment by syedmizanur** [comment] 2022-06-26 11:05
Thats odd. I cannot find any download links on the link 
https://build.sailfishos.org/package/binary/home:msameer:sailfish:apps/harbour-quran?arch=aarch64&filename=harbour-quran-0.7.0%2Bmaster.20220623205801.153.g93f59d6-118.1.aarch64.rpm&repository=sailfishos_latest_latest_aarch64
![image](https://user-images.githubusercontent.com/59015446/175811041-7ed39ded-7fc9-49fe-b843-7baf1ec5ca92.png)

What I can actually do is go to the repository state and click on "go to download repository" which results in the 404 error.

I would love to help from my side and now that I have two devices (Xperia X I and III), I could help you with the end user testing even with dev mode on for that matter. However, mobile app development/publishing are really quite alien to me. Hence, I could not really do anything more.

BTW, is the Andriod version available of FDroid/Aptoid?

Best Regards,
Syed

**Comment by foolab** [comment] 2022-06-26 11:56
The RPM name should be clickable (I know it's confusing) :)
![quran-rpm](https://user-images.githubusercontent.com/1503028/175812657-016d087e-830c-4218-aaed-5a0cb08469bf.png)

I really have no idea why the repository is empty. OBS should publish the built binaries to it but it is not for an unknown reason.

I'd appreciate any help. I have an aqua fish but I do not know if it's supported or not. My latest submission to harbour was rejected a few years ago because my app does not meet the Sailfish OS UI guidelines. Perhaps openrepos could be the solution.

I have not published the Android APK anywhere. I was working on implementing audio playback but I still have some issues to iron out.

**Comment by syedmizanur** [comment] 2022-06-26 12:39
The name isnt't clickable for me. The html shows its just h3 
![image](https://user-images.githubusercontent.com/59015446/175814446-ef091581-efa1-4b7d-9f56-0ef87d1c7432.png)
Perhaps its because I'm not logged in? There is no option to register either (I'm guessing one has to be invited by the admin)

Best,
Syed

**Comment by foolab** [comment] 2022-06-26 12:46
It could be that you are not logged in.

Anyway, I uploaded the RPM here for now:
https://foolab.org/harbour-quran-0.7.0+master.20220623205801.153.g93f59d6-118.1.aarch64.rpm

**Comment by syedmizanur** [comment] 2022-06-26 15:10
It seems to work! Here are the Screenshots from the Xperia X iii..

Thanks a lot. May your efforts be accepted. 

Best,
Syed

![image](https://user-images.githubusercontent.com/59015446/175820835-c0b70469-2366-439f-85a8-60167766e1dd.png)
![image](https://user-images.githubusercontent.com/59015446/175820842-5ce7076e-616b-4e3d-adf2-d0e6337916b5.png)

**Comment by foolab** [comment] 2022-06-26 15:27
This is good to hear :)

I submitted issue #3 about moving to openrepos. Feel free to follow it.

And please feel free to open an issue if you find something that is not working.

Jazakom Allah khair

**Closed as completed by foolab** 2022-06-26 15:27 UTC

**Comment by syedmizanur** [comment] 2022-06-26 18:05
Will do. Do carry on your good work!

**Comment by syedmizanur** [comment] 2022-10-11 07:53
It seems to work. Here are the Screenshots from the Xperia X iii..

Thanks a lot. May your efforts be accepted. 

Best,
Syed

Am Sonntag, 26. Juni 2022 schrieb Mohammed Sameer:
> It could be that you are not logged in.
> 
> Anyway, I uploaded the RPM here for now:
> https://foolab.org/harbour-quran-0.7.0+master.20220623205801.153.g93f59d6-118.1.aarch64.rpm
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/foolab/quran/issues/2#issuecomment-1166522193
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Gesendet von meinem Sailfish Gerät
